set search_path to hr, oe

show search_path

-- Task 1

-- Create table table & relasinya untuk table bank,users,carts,cart_items 
-- & attribute tambahan yang ada di table orders.

-- Create table : bank
create table oe.bank (
	bank_code varchar(4) primary key,
	bank_name varchar(55)
);

-- Create table : users
create table oe.users(
	user_id integer primary key,
	user_name varchar(15),
	user_email varchar(80) unique,
	user_password varchar(125),
	user_handphone varchar(15) unique,
	created_on timestamp default current_timestamp
)

alter table oe.users
	alter column user_name type varchar(40),
	alter column user_handphone type varchar(24)

select * from oe.users

-- Create table : carts
create table oe.carts(
	cart_id smallint primary key,
	created_on timestamp default current_timestamp,
	user_id integer unique,
	constraint user_id_fk foreign key (user_id) references oe.users(user_id)
)

-- Create table : cart_items
create table oe.cart_items(
	cart_item_id smallint primary key,
	product_id integer unique,
	quantity smallint,
	created_on timestamp default current_timestamp,
	cart_id integer,
	constraint cart_id_fk foreign key (cart_id) references oe.carts(cart_id)
)

-- Update table : orders
alter table oe.orders
	add column order_no varchar(15),
	add column total_discount decimal(5,2),
	add column total_amount decimal(8,2),
	add column payment_type varchar(15),
	add column card_no varchar(25),
	add column transac_no varchar(25),
	add column transac_date timestamp,-- ini harusnya ditambahain default current_timestamp
	add column ref_no varchar(25),

	add column location_id integer,
	add column user_id integer,
	add column bank_code varchar(4),

	add constraint location_id_fk foreign key (location_id) references hr.locations(location_id),
	add constraint user_id_fk foreign key (user_id) references oe.users(user_id),
	add constraint bank_code_fk foreign key (bank_code) references oe.bank(bank_code)

alter table oe.orders
-- Task 2

-- Buat link antara table hr.locations dan table oe.orders, 
-- dan update kolom location_id di table oe.orders.
-- 
-- Untuk link sudah dilakukan pada saat Task 1

-- Set value dari kolom location_id pada tabel orders
-- dengan nilai dari tabel hr.locations

update oe.orders as o
set location_id = null

update oe.orders as o
set location_id = (
	select location_id from location_x l
	where 
		o.ship_address=l.street_address and 
		o.ship_city=l.city and
		o.ship_region=l.state_province and
		o.ship_postal_code=l.postal_code and
		o.ship_country=l.country_name
) where o.location_id is null

select * from oe.orders
where location_id is not null
limit(10)

--Task 3 

insert into hr.employees (employee_id, first_name, last_name, email, hire_date, job_id, salary)
select employee_id, first_name, last_name, lower(first_name||  '.' || last_name || '@sqltutorial.com')
as email, hire_date, j.job_id,
0.00 as salary
from oe.employees
join (
    select job_id
    from hr.jobs
    order by RANDOM()
	limit 1
) j on TRUE;
select * from hr.employees

-- Buat relasi antara table hr.employees dengan table oe.orders

alter table oe.orders
add constraint employee_id foreign key(employee_id) 
references hr.employees(employee_id) 

--Task 4

-- pindahkan data dari table oe.customer ke table users
-- buat relasi antara table oe.users dengan table oe.orders
CREATE EXTENSION IF NOT EXISTS pgcrypto;

alter table oe.users
alter column user_id add generated by default as identity

insert into oe.users (user_name,user_password,user_handphone) 
select
	contact_name , 
	crypt(lower(oc.customer_id), gen_salt('bf', 12)),
	phone 
from oe.customers oc

select * from oe.users